---
global:
  spec:
    namespace: argocd
    source:
      repoURL: https://github.com/muhlba91/homelab-kubernetes-public-applications.git
      targetRevision: HEAD
    values:
      repoURL: git@github.com:muhlba91/homelab-kubernetes-public-values.git
      targetRevision: HEAD
    syncWave: 0
    helm:
      enabled: false
      valueFiles:
        - values.yaml
    enableAutomated: true
    syncOptions: []

applications:
  argocd:
    project: "infrastructure-{{ $.Values.global.projectEnvironment }}"
    path: infrastructure/charts/argocd
    disabled: false
    namespace: argocd
    releaseName: argocd-{{ $.Values.global.environment }}
    helm: true
    syncWave: -2000
  cilium:
    project: "infrastructure-{{ $.Values.global.projectEnvironment }}"
    path: infrastructure/charts/cilium
    releaseName: cilium
    disabled: false
    namespace: cilium
    helm: true
    syncWave: -1000
  external-secrets:
    project: "infrastructure-{{ $.Values.global.projectEnvironment }}"
    path: infrastructure/charts/external-secrets
    releaseName: external-secrets
    disabled: false
    namespace: external-secrets
    helm: true
    syncWave: -750
  external-secrets-stores:
    project: "infrastructure-{{ $.Values.global.projectEnvironment }}"
    path: infrastructure/kustomizations/external-secrets-stores
    releaseName: external-secrets-stores
    disabled: false
    namespace: external-secrets
    helm: false
    syncWave: -500
  descheduler:
    project: "infrastructure-{{ $.Values.global.projectEnvironment }}"
    path: infrastructure/charts/descheduler
    releaseName: descheduler
    disabled: false
    namespace: descheduler
    helm: true