---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-authentik
  target:
    name: authentik-secrets
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: SECRET_KEY
    - secretKey: AUTHENTIK_EMAIL__FROM
      remoteRef:
        key: EMAIL_FROM
