---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-email-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-email
  target:
    name: authentik-email-config
  data:
    - secretKey: AUTHENTIK_EMAIL__HOST
      remoteRef:
        key: MXROUTE_HOST
    - secretKey: AUTHENTIK_EMAIL__PORT
      remoteRef:
        key: MXROUTE_PORT
    - secretKey: AUTHENTIK_EMAIL__USE_SSL
      remoteRef:
        key: MXROUTE_USE_SSL
    - secretKey: AUTHENTIK_EMAIL__USE_TLS
      remoteRef:
        key: MXROUTE_USE_TLS
    - secretKey: AUTHENTIK_EMAIL__USERNAME
      remoteRef:
        key: MXROUTE_USERNAME
    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      remoteRef:
        key: MXROUTE_PASSWORD
