apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: doppler-auth-authentik
data:
    token: ENC[AES256_GCM,data:ZgWdkuvyWWd2oWb8LOo1AQ8DZXjZ3/Hnxa+SUs73w7X9kenm4zpbClLHjOmJgKfX6X92OESH2zpM827vlsAIv0nVABTK7Oyc,iv:gxuM25iC7VRwVhtHpDQaPTy6woJtmyoUjVTDnU4ukG8=,tag:LqXolpgiyvpA7PJVcRiRtQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/tuxnet-385112/locations/europe/keyRings/infrastructure-encryption/cryptoKeys/infrastructure-encryption
          created_at: "2023-05-14T10:14:27Z"
          enc: CiQA9PdEcGDg9+2cDjo8AqDutVB3xhRVPOj4eClUzhMSJC7cLl8SSQA2N6cCWmH0FzF1YmIBCx8QPZPSbjuWADxUJ0AmZqNsfbeGEhvOkNezLAOAVKbzmCEZJy1yRtqgXuvTTYnxW5mlzS1avHWoqO0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-14T10:14:27Z"
    mac: ENC[AES256_GCM,data:Mf4WGSkyxIb3d1ODW1bYzlm+q+SDu80OlfmjLjhHzn+PdIx10NRwAYMUBVHEIyApbxRLtr7oIZ3eRSrewsShLWYzPcUE8zmdaEJIJIQ3or9mTbSvZlVp3GLZb6rYsEdlztLG7347jcWJXKq6P1jdPkjvIBd7yrThXwVbD10k9s0=,iv:efsN9R2GwqfbbdbsM5CJoGroF9vkqvniCNQZHqxAR1E=,tag:DFUWnvz+OsYI7KuuC3vokQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
