apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: doppler-auth-email
data:
    token: ENC[AES256_GCM,data:C8L1ZOrBnJr0sj7uhCbP9YHc5KPN1Fsp2o4sHZRjYc6mIqfWr6yWooWL83gOk35J0gP3kgtjoYKzdXe6ypzXFEl9B3BynHU+,iv:nTPcyrjRQwOlEW3oQIlcsO+wYsmKEHyjQ8tlwIJtmVk=,tag:P9rny2WSDh4pk6MBeSSWqw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/tuxnet-385112/locations/europe/keyRings/infrastructure-encryption/cryptoKeys/infrastructure-encryption
          created_at: "2023-05-14T10:18:32Z"
          enc: CiQA9PdEcA1KXvFkd63dAXo1TiMb6A/DVV9QsvE5AY6ayHqNrHYSSQA2N6cCSEEzFyUg1n5GGVtlB+CoKx/l67avgNNK4Z3blIv4yIHeKYRh7YTkjxgc7G7j22MNeQ9COKIKAoRL6VT9aMaIS652U78=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-14T10:18:32Z"
    mac: ENC[AES256_GCM,data:QTSc3Lci7K+qUGsl4HT3OkB3ter1bTrPqBgBda+NAFvgzLTMZsROBXBrgn1AVuy1cGFAmEfA6QV/mrop46y+LMO71HBQWqh8TaMlJJeemkK/2FxdY6LsAsHJ6qdPDQ5myw0UXGUurM3Cf84LnVRP94qV3fkq2qYfCZf9ktGBEno=,iv:LvZmh6DR8JTQpc+olU6iMn/pX4o5v8f6/G6oP8iSkKk=,tag:uKVDSosKX/Icu7GsdcQxPg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
