---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-github
  target:
    name: actions-runner-controller-auth
  data:
    - secretKey: github_token
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: GITHUB_ACTIONS_RUNNER_CONTROLLER_TOKEN
