{{- range .Values.runners.organizations }}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: organization-runner-{{ .organization | replace "/" "--" }}
spec:
  template:
    spec:
      replicas: {{ default $.Values.runnerConfig.replicas .replicas }}
      organization: {{ .organization }}
    {{- with .labels }}
      labels: {{ . | toYaml |  nindent 8 }}
    {{- end }}
{{- end }}
