{{- range .Values.runners.repositories }}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .repository | replace "/" "--" }}
spec:
  replicas: {{ default $.Values.runnerConfig.replicas .replicas }}
  template:
    spec:
      ephemeral: true
      containers:
        - name: docker
          resources: {}
          env:
            RUNNER_TOOL_CACHE: /runner/_work/hostedtoolcache
        - name: runner
          resources: {}
          env:
            RUNNER_TOOL_CACHE: /runner/_work/hostedtoolcache
      repository: {{ .repository }}
    {{- with .labels }}
      labels: {{ . | toYaml |  nindent 8 }}
    {{- end }}
{{- end }}
