{{- range .Values.runners.repositories }}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .repository | replace "/" "--" }}
spec:
  replicas: {{ default $.Values.runnerConfig.replicas .replicas }}
  template:
    spec:
      ephemeral: true
      volumeMounts:
        - mountPath: /opt/hostedtoolcache
          name: tool-cache
      volumes:
        - name: tool-cache
          emptyDir: {}
      repository: {{ .repository }}
    {{- with .labels }}
      labels: {{ . | toYaml |  nindent 8 }}
    {{- end }}
{{- end }}
