{{- range .Values.runners.repositories }}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: repository-runner-{{ .repository | replace "/" "--" }}
spec:
  replicas: {{ default $.Values.runnerConfig.replicas .replicas }}
  template:
    spec:
      repository: {{ .repository }}
    {{- with .labels }}
      labels: {{ . | toYaml |  nindent 8 }}
    {{- end }}
{{- end }}
