---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-scripts
data:
  secret.sh: |
    #!/bin/sh
    
    sed "s/#NODE_NAME#/${NODE_NAME}/g" -r /scripts/tailscale-state.yml > /tmp/tailscale-state.yml
    kubectl create -f /tmp/tailscale-state.yml || true
  tailscale-state.yml: |
    ---
    apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: #NODE_NAME#
