---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-tailscale
  target:
    name: tailscale-secrets
  data:
    - secretKey: auth-key
      remoteRef:
        key: TS_AUTH_KEY
