---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccountName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
roleRef:
  kind: Role
  name: {{ .Values.serviceAccountName }}
  apiGroup: rbac.authorization.k8s.io
