---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceAccountName }}
rules:
  - apiGroups: [""]
    resourceNames: [""]
    resources:
      - secrets
    verbs:
      - create
      - get
      - update
      - patch
